# Form implementation generated from reading ui file 'prompt_ui.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(711, 314)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(500, 0))
        Form.setBaseSize(QtCore.QSize(300, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(500, 200)) # Increased minimum height
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        
        # Main Vertical Layout for the Frame
        self.frameLayout = QtWidgets.QVBoxLayout(self.frame)
        self.frameLayout.setObjectName("frameLayout")

        # Header Row: Name Input + Delete Button
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        
        self.promptNameInput = QtWidgets.QLineEdit(parent=self.frame)
        self.promptNameInput.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed))
        self.promptNameInput.setObjectName("promptNameInput")
        self.headerLayout.addWidget(self.promptNameInput)

        self.removePromptButton = QtWidgets.QToolButton(parent=self.frame)
        self.removePromptButton.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed))
        self.removePromptButton.setObjectName("removePromptButton")
        self.headerLayout.addWidget(self.removePromptButton)
        
        self.frameLayout.addLayout(self.headerLayout)

        # Body: Target Field, Pin, Text Area
        self.targetFieldInput = QtWidgets.QLineEdit(parent=self.frame)
        self.targetFieldInput.setObjectName("targetFieldInput")
        self.frameLayout.addWidget(self.targetFieldInput)
        
        # New: Response Format Selector
        self.responseFormatLayout = QtWidgets.QHBoxLayout()
        self.labelResponseFormat = QtWidgets.QLabel("Response Format:", parent=self.frame)
        self.responseFormat = QtWidgets.QComboBox(parent=self.frame)
        self.responseFormat.addItems(["Text", "JSON"])
        self.responseFormat.setObjectName("responseFormat")
        self.responseFormatLayout.addWidget(self.labelResponseFormat)
        self.responseFormatLayout.addWidget(self.responseFormat)
        self.responseFormatLayout.addStretch()
        self.frameLayout.addLayout(self.responseFormatLayout)
        
        # New: Field Mapping Input (Hidden by default or managed by logic)
        self.fieldMappingInput = QtWidgets.QPlainTextEdit(parent=self.frame)
        self.fieldMappingInput.setPlaceholderText("JSON Mapping (Key: Field Name)\nExample:\ntranslation: Word Translation\nipa: IPA Field")
        self.fieldMappingInput.setMaximumHeight(100)
        self.fieldMappingInput.setObjectName("fieldMappingInput")
        self.frameLayout.addWidget(self.fieldMappingInput)
        
        self.pinnedCheckbox = QtWidgets.QCheckBox(parent=self.frame)
        self.pinnedCheckbox.setText("Pin to Menu")
        self.pinnedCheckbox.setObjectName("pinnedCheckbox")
        self.frameLayout.addWidget(self.pinnedCheckbox)

        self.promptInput = QtWidgets.QTextEdit(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setVerticalStretch(1) # Give it stretch priority
        self.promptInput.setSizePolicy(sizePolicy)
        self.promptInput.setMinimumSize(QtCore.QSize(0, 100)) # Ensure reasonable height
        self.promptInput.setAcceptRichText(False)
        self.promptInput.setObjectName("promptInput")
        self.frameLayout.addWidget(self.promptInput)
        
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.promptNameInput.setPlaceholderText(_translate("Form", "Prompt Name"))
        self.targetFieldInput.setPlaceholderText(_translate("Form", "Target Field"))
        self.promptInput.setPlaceholderText(_translate("Form", "Prompt"))
        self.removePromptButton.setToolTip(_translate("Form", "Remove this prompt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())